name: Build main

on:
  push:
    paths:
      - 'main.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'main.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Find available port
      id: find-port
      run: echo "::set-output name=port::$(shuf -i 8000-9000 -n 1)"

    - name: Run Flask app
      run: |
        export FLASK_APP=main.py
        export FLASK_RUN_PORT=${{ steps.find-port.outputs.port }}
        flask run --host=0.0.0.0 --port=${FLASK_RUN_PORT} &
        sleep 3  # Give Flask a few seconds to start
        curl http://localhost:${FLASK_RUN_PORT}/  # Send a request to verify the server is running

    - name: Build main.py
      run: |
        python main.py
