# Ce workflow GitHub Action construit une image Docker à partir du fichier Dockerfile
# lorsqu'il est déclenché manuellement. L'image est configurée pour prendre en charge
# les plates-formes Linux/amd64 et Linux/arm64.

name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t LionelKhoi/CICD_Project:latest .
      env:
        DOCKER_CLI_AGGREGATE: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
