name: Docker push GCR

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Set up Cloud Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_JSON }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: esirem

      - name: Configure Docker using GCLOUD
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.3.1
        with:
          file: Dockerfile
          tags: europe-west1-docker.pkg.dev/esirem/esirem/4A_ilc/benameur_nguyen/${{ steps.to_lower.outputs.repository }}:${{ github.ref_name }}
          context: .
          push: true
