name: Docker push GCR

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Set up Cloud Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_JSON }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: esirem

      - name: Configure Docker using GCLOUD
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Determine ref type and convert to lowercase
        run: |
          if [[ "${{ github.event_name }}" == "push" && -n "${{ github.event.ref }}" ]]; then
            REF_NAME=$(echo "${{ github.event.ref }}" | sed 's|refs/heads/||' | tr '[:upper:]' '[:lower:]')
          elif [[ "${{ github.event_name }}" == "push" && -n "${{ github.event.ref_type }}" && "${{ github.event.ref_type }}" == "tag" ]]; then
            REF_NAME=$(echo "${{ github.event.ref }}" | sed 's|refs/tags/||' | tr '[:upper:]' '[:lower:]')
          fi
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.3.1
        with:
          file: Dockerfile
          tags: europe-west1-docker.pkg.dev/${{ env.REPO_NAME }}/4A_ilc/benameur_nguyen/cicd_project:${{ env.REF_NAME }}
          context: .
          push: true
